feat: Added allow overwrite option to adwords reports to s3 util
hipagesgroup/data-tools pull request #125
Opened 2020-08-27 09:19 UTC by vbmudalige

### What changes are proposed in this PR?
---
* Added allow overwrite option to adwords reports to s3 util 

### How was this tested?
---
* N/A

2020-08-28 03:45 UTC, arihantsurana requested changes

2020-08-28 03:45 UTC, arihantsurana commented on hip_data_tools/etl/adwords_to_athena.py
>          super().__init__(settings)
```suggestion
        settings.target_key_prefix = get_target_prefix_with_partition_dirs()
        super().__init__(settings)
```

2020-08-28 03:45 UTC, arihantsurana commented on hip_data_tools/etl/adwords_to_athena.py
> +    return target_key_prefix
```suggestion
def get_target_prefix_with_partition_dirs() -> str:
    """
    Calculate the target s3 key prefix including partition directories
    fix docstring, use the google python standard
    """
    if self.__settings.partition_values:
        partition_dirs = "/".join([f"{k}={v}" for k, v in self.__settings.partition_values])
        return f"{target_key_prefix}/{partition_dirs}"
    return target_key_prefix
```

2020-08-28 05:01 UTC, vbmudalige commented on hip_data_tools/etl/adwords_to_athena.py
>          super().__init__(settings)
fixed

2020-08-28 05:02 UTC, vbmudalige commented on hip_data_tools/etl/adwords_to_athena.py
> +    return target_key_prefix
fixed

2020-08-28 05:29 UTC, arihantsurana approved these changes

2020-08-28 05:30 UTC, merged

2020-10-30 12:00 UTC, willmeet commented
[How to get $350 threshold from google adwords without credit card or bank account Free Trick 2020](http://www.technologymanias.com/2020/10/how-to-get-350-threshold-from-google.html)